// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pb/oneof.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sub1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Sub1) Reset() {
	*x = Sub1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_oneof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sub1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub1) ProtoMessage() {}

func (x *Sub1) ProtoReflect() protoreflect.Message {
	mi := &file_pb_oneof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub1.ProtoReflect.Descriptor instead.
func (*Sub1) Descriptor() ([]byte, []int) {
	return file_pb_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *Sub1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Sub2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Sub2) Reset() {
	*x = Sub2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_oneof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sub2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub2) ProtoMessage() {}

func (x *Sub2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_oneof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub2.ProtoReflect.Descriptor instead.
func (*Sub2) Descriptor() ([]byte, []int) {
	return file_pb_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *Sub2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SampleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TestOneof:
	//	*SampleMessage_Sub1
	//	*SampleMessage_Sub2
	TestOneof isSampleMessage_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *SampleMessage) Reset() {
	*x = SampleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_oneof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMessage) ProtoMessage() {}

func (x *SampleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_oneof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMessage.ProtoReflect.Descriptor instead.
func (*SampleMessage) Descriptor() ([]byte, []int) {
	return file_pb_oneof_proto_rawDescGZIP(), []int{2}
}

func (m *SampleMessage) GetTestOneof() isSampleMessage_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *SampleMessage) GetSub1() *Sub1 {
	if x, ok := x.GetTestOneof().(*SampleMessage_Sub1); ok {
		return x.Sub1
	}
	return nil
}

func (x *SampleMessage) GetSub2() *Sub2 {
	if x, ok := x.GetTestOneof().(*SampleMessage_Sub2); ok {
		return x.Sub2
	}
	return nil
}

type isSampleMessage_TestOneof interface {
	isSampleMessage_TestOneof()
}

type SampleMessage_Sub1 struct {
	Sub1 *Sub1 `protobuf:"bytes,1,opt,name=sub1,proto3,oneof"`
}

type SampleMessage_Sub2 struct {
	Sub2 *Sub2 `protobuf:"bytes,2,opt,name=sub2,proto3,oneof"`
}

func (*SampleMessage_Sub1) isSampleMessage_TestOneof() {}

func (*SampleMessage_Sub2) isSampleMessage_TestOneof() {}

var File_pb_oneof_proto protoreflect.FileDescriptor

var file_pb_oneof_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x53, 0x75, 0x62, 0x31, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x53, 0x75, 0x62, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x63, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x21, 0x0a, 0x04, 0x73, 0x75, 0x62, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x31, 0x48, 0x00, 0x52, 0x04, 0x73,
	0x75, 0x62, 0x31, 0x12, 0x21, 0x0a, 0x04, 0x73, 0x75, 0x62, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x32, 0x48, 0x00,
	0x52, 0x04, 0x73, 0x75, 0x62, 0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x67, 0x6f, 0x2d,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x64, 0x61, 0x79, 0x32, 0x31, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_oneof_proto_rawDescOnce sync.Once
	file_pb_oneof_proto_rawDescData = file_pb_oneof_proto_rawDesc
)

func file_pb_oneof_proto_rawDescGZIP() []byte {
	file_pb_oneof_proto_rawDescOnce.Do(func() {
		file_pb_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_oneof_proto_rawDescData)
	})
	return file_pb_oneof_proto_rawDescData
}

var file_pb_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_oneof_proto_goTypes = []interface{}{
	(*Sub1)(nil),          // 0: hello.Sub1
	(*Sub2)(nil),          // 1: hello.Sub2
	(*SampleMessage)(nil), // 2: hello.SampleMessage
}
var file_pb_oneof_proto_depIdxs = []int32{
	0, // 0: hello.SampleMessage.sub1:type_name -> hello.Sub1
	1, // 1: hello.SampleMessage.sub2:type_name -> hello.Sub2
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_oneof_proto_init() }
func file_pb_oneof_proto_init() {
	if File_pb_oneof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_oneof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sub1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_oneof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sub2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_oneof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_oneof_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SampleMessage_Sub1)(nil),
		(*SampleMessage_Sub2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_oneof_proto_goTypes,
		DependencyIndexes: file_pb_oneof_proto_depIdxs,
		MessageInfos:      file_pb_oneof_proto_msgTypes,
	}.Build()
	File_pb_oneof_proto = out.File
	file_pb_oneof_proto_rawDesc = nil
	file_pb_oneof_proto_goTypes = nil
	file_pb_oneof_proto_depIdxs = nil
}
